#!/bin/bash

# set variables
path_root="/mnt/user/appdata"
path_rpc="/boot/config/myscripts/rpc.json"

# read parameters from rpc.json file
jq -M -r '
    .[] | .coin_name, .fullnode_port
' < "${path_rpc}" | \

while read -r coin_name; read -r fullnode_port;do

case "${coin_name}" in
	nchain)
	config_path="ext9" ;;
	*)
	config_path="mainnet" ;;
esac ;

sync_state=$(curl --silent --insecure \
--cert "${path_root}/${coin_name}/${config_path}/config/ssl/full_node/private_full_node.crt" \
--key "${path_root}/${coin_name}/${config_path}/config/ssl/full_node/private_full_node.key" \
-d '{}' -H "Content-Type: application/json" \
-X POST "https://localhost:${fullnode_port}/get_blockchain_state" \
| jq '.blockchain_state.sync.synced');

case "${sync_state}" in
        false)
        output_colour="1" ;; # output red
        true)
        output_colour="2" ;; # output green
esac ;

echo "$(tput sgr0) ${coin_name} Current Blockchain Status: Full Node Synced $(tput setaf $output_colour)${sync_state}"
done
