#!/bin/bash

# set variables
path_root="/mnt/user/appdata"
path_rpc="/boot/config/myscripts/rpc.json"
divisor="1000000000000"
precision="12"

# read parameters from rpc.json file
jq -M -r '
    .[] | .coin_name, .wallet_port
' < "${path_rpc}" | \

while read -r coin_name; read -r wallet_port;do

case "${coin_name}" in
	nchain)
	config_path="ext9" ;;
	*)
	config_path="mainnet" ;;
esac ;

# match coin names for operation
case "${coin_name}" in
	ecostake|gold|profit|petroleum|silicoin)

rpc_balance=$(curl --silent --insecure \
--cert "${path_root}/${coin_name}/${config_path}/config/ssl/full_node/private_full_node.crt" \
--key "${path_root}/${coin_name}/${config_path}/config/ssl/full_node/private_full_node.key" \
-d '{"wallet_id": 1}' -H "Content-Type: application/json" \
-X POST "https://localhost:${wallet_port}/get_wallet_balance" \
| jq '.wallet_balance.spendable_balance');

[[ "${rpc_balance}" == ?(-)+([[:digit:]]) ]] || rpc_balance="0"

balance=$(awk "BEGIN {printf \"%.${precision}f\n\", ${rpc_balance}/${divisor}}" | sed '/\./ s/\.\{0,1\}0\{1,\}$//')

echo "${coin_name} Spendable balance: ${balance}";;

# no op for match coin names
*)
: ;;
esac ;
done
