#!/bin/bash

# set variables
path_root="/mnt/user/appdata"
path_rpc="/boot/config/myscripts/rpc.json"
re='^[0-9]+$'

# read parameters from rpc.json file
jq -M -r '
    .[] | .coin_name, .wallet_port
' < "${path_rpc}" | \

while read -r coin_name; read -r wallet_port;do

case "${coin_name}" in
	nchain)
	config_path="ext9" ;;
	*)
	config_path="mainnet" ;;
esac ;

if ! [[ $wallet_port =~ $re ]] ; then
:
else

wallet_sync=$(curl --silent --insecure \
--cert "${path_root}/${coin_name}/${config_path}/config/ssl/full_node/private_full_node.crt" \
--key "${path_root}/${coin_name}/${config_path}/config/ssl/full_node/private_full_node.key" \
-d '{"wallet_id": 1}' -H "Content-Type: application/json" \
-X POST "https://localhost:${wallet_port}/get_sync_status" \
| jq '.synced');

case "${wallet_sync}" in
	true)
        output_colour="2" ;; # output green
        *)
        wallet_sync="false";
        output_colour="1" ;; # output red
esac ;

echo "$(tput sgr0) ${coin_name} Wallet Synced: $(tput setaf $output_colour)${wallet_sync}"
fi
done
